"""Regression test: after user regenerates outputs post-prompt-rework, no
WHITE_HEADER / NOTE_ROW / BLANK row may contain a numeric value.

This test is strict-by-default but marks the historical pre-regen
outputs as xfail so CI stays green until the user regenerates. Remove
the xfail entries as each company's output is regenerated.
"""
from __future__ import annotations
import json
from pathlib import Path

import openpyxl
import pytest

REPO = Path(__file__).resolve().parents[4]
CELL_TYPES = json.loads((REPO / "DOCS" / "cma_cell_types.json").read_text(encoding="utf-8"))
FORBIDDEN_TYPES = {"WHITE_HEADER", "NOTE_ROW", "BLANK"}

# Rows that META classifies as writable text (R11-15: FY, Currency, Units, Auditors, Opinion).
# These are correctly populated with strings by the extraction step, not classification.
META_SAFE_ROWS = {11, 12, 13, 14, 15}

# Outputs we know were generated by the OLD pipeline. Mark xfail until regenerated.
PRE_REGEN_OUTPUTS = {
    # Populated from the Phase 5 baseline scan — rewrite this set as outputs regenerate.
    "CMA_Extraction_v2/output.xlsm",
}

OUTPUT_FILES = sorted(
    p for p in (REPO / "CMA_Extraction_v2").rglob("*.xlsm")
    if not p.name.startswith("~")
)


def _find_bad_fills(output_path: Path) -> list[tuple]:
    wb = openpyxl.load_workbook(str(output_path), keep_vba=True, data_only=False)
    if "INPUT SHEET" not in wb.sheetnames:
        return []
    ws = wb["INPUT SHEET"]
    bad = []
    for r_str, info in CELL_TYPES["rows"].items():
        if info["type"] not in FORBIDDEN_TYPES:
            continue
        r = int(r_str)
        if r in META_SAFE_ROWS:
            continue
        for col in range(2, 9):
            v = ws.cell(row=r, column=col).value
            if v in (None, "", 0):
                continue
            if isinstance(v, str) and v.startswith("="):
                continue
            if isinstance(v, (int, float)):
                bad.append((r, info["type"], info.get("label"), chr(64 + col), v))
    return bad


@pytest.mark.parametrize(
    "output_path",
    OUTPUT_FILES,
    ids=[str(p.relative_to(REPO)) for p in OUTPUT_FILES],
)
def test_no_bad_fills(output_path: Path):
    rel = str(output_path.relative_to(REPO)).replace("\\", "/")
    bad = _find_bad_fills(output_path)
    if rel in PRE_REGEN_OUTPUTS and bad:
        pytest.xfail(f"Pre-regen output — {len(bad)} bad fills remaining. Regenerate.")
    assert not bad, (
        f"Bad fills found in {rel}:\n" + "\n".join(
            f"  R{r} [{t}] [{c}] {l} = {v}" for r, t, l, c, v in bad
        )
    )
