"""Maps CMA field names to exact row numbers in the INPUT SHEET.

These mappings come from the CMA.xlsm template analysis (spec Section 12).
P&L section: rows 17-109
Balance Sheet section: rows 111-262
"""

PNL_FIELD_TO_ROW: dict[str, int] = {
    "Domestic Sales": 22,
    "Export Sales": 23,
    "Less Excise Duty and Cess": 25,
    "Dividends received from Mutual Funds": 29,
    "Interest Received": 30,
    "Profit on sale of fixed assets / Investments": 31,
    "Gain on Exchange Fluctuations": 32,
    "Extraordinary income": 33,
    "Others (Non-Operating Income)": 34,
    "Raw Materials Consumed (Imported)": 41,
    "Raw Materials Consumed (Indigenous)": 42,
    "Stores and spares consumed (Imported)": 43,
    "Stores and spares consumed (Indigenous)": 44,
    "Wages": 45,
    "Processing / Job Work Charges": 46,
    "Freight and Transportation Charges": 47,
    "Power, Coal, Fuel and Water": 48,
    "Others (Manufacturing)": 49,
    "Repairs & Maintenance (Manufacturing)": 50,
    "Security Service Charges": 51,
    "Stock in process Opening Balance": 53,
    "Stock in process Closing Balance": 54,
    "Depreciation (Manufacturing)": 56,
    "Finished Goods Opening Balance": 58,
    "Finished Goods Closing Balance": 59,
    "Depreciation (CMA)": 63,
    "Other Manufacturing Exp (CMA)": 64,
    "Salary and staff expenses": 67,
    "Rent, Rates and Taxes": 68,
    "Bad Debts": 69,
    "Advertisements and Sales Promotions": 70,
    "Others (Admin)": 71,
    "Repairs & Maintenance (Admin)": 72,
    "Audit Fees & Directors Remuneration": 73,
    "Miscellaneous Expenses written off": 75,
    "Deferred Revenue Expenditures": 76,
    "Other Amortisations": 77,
    "Interest on Fixed Loans / Term loans": 83,
    "Interest on Working capital loans": 84,
    "Bank Charges": 85,
    "Loss on sale of fixed assets / Investments": 89,
    "Sundry Balances Written off": 90,
    "Loss on Exchange Fluctuations": 91,
    "Extraordinary losses": 92,
    "Others (Non-Operating Expenses)": 93,
    "Income Tax provision": 99,
    "Deferred Tax Liability (P&L)": 100,
    "Deferred Tax Asset (P&L)": 101,
    "Brought forward from previous year": 106,
    "Dividend": 107,
    "Other Appropriation of profit": 108,
}

BS_FIELD_TO_ROW: dict[str, int] = {
    "Issued, Subscribed and Paid up": 116,
    "Share Application Money": 117,
    "General Reserve": 121,
    "Balance transferred from profit and loss a/c": 122,
    "Share Premium A/c": 123,
    "Revaluation Reserve": 124,
    "Other Reserve": 125,
    "Working Capital Bank Finance - Bank 1": 131,
    "Working Capital Bank Finance - Bank 2": 132,
    "Term Loan Repayable in next one year": 136,
    "Term Loan Balance Repayable after one year": 137,
    "Debentures Repayable in next one year": 140,
    "Debentures Balance Repayable after one year": 141,
    "Preference Shares Repayable in next one year": 144,
    "Preference Shares Balance Repayable after one year": 145,
    "Other Debts Repayable in Next One year": 148,
    "Balance Other Debts": 149,
    "Unsecured Loans - Quasi Equity": 152,
    "Unsecured Loans - Long Term Debt": 153,
    "Unsecured Loans - Short Term Debt": 154,
    "Deferred tax liability (BS)": 159,
    "Gross Block": 162,
    "Less Accumulated Depreciation": 163,
    "Capital Work in Progress": 165,
    "Patents / goodwill / copyrights etc": 169,
    "Misc Expenditure (to the extent not w/o)": 170,
    "Deferred Tax Asset (BS)": 171,
    "Other Intangible assets": 172,
    "Additions to Fixed Assets": 175,
    "Sale of Fixed assets WDV": 176,
    "Profit on sale of Fixed assets (BS)": 177,
    "Loss on sale of Fixed assets (BS)": 178,
    "Investment in Govt. Securities (Current)": 182,
    "Investment in Govt. Securities (Non Current)": 183,
    "Other current investments": 185,
    "Other non current investments": 186,
    "Investment in group companies / subsidiaries": 188,
    "Raw Material Imported": 193,
    "Raw Material Indigenous": 194,
    "Stores and Spares Imported": 197,
    "Stores and Spares Indigenous": 198,
    "Stocks-in-process": 200,
    "Finished Goods": 201,
    "Domestic Receivables": 206,
    "Export Receivables": 207,
    "Debtors more than 6 months": 208,
    "Cash on Hand": 212,
    "Bank Balances": 213,
    "Fixed Deposit under lien": 214,
    "Other Fixed Deposits": 215,
    "Advances recoverable in cash or in kind": 219,
    "Advances to suppliers of raw materials": 220,
    "Advance Income Tax": 221,
    "Prepaid Expenses": 222,
    "Other Advances / current asset": 223,
    "Advances to group / subsidiaries companies": 224,
    "Exposure in group companies - Investments": 229,
    "Exposure in group companies - Advances": 230,
    "Debtors more than six months (Non-Current)": 232,
    "Investments (Non-Current)": 233,
    "Fixed Deposits (Non Current)": 234,
    "Dues from directors / partners / promoters": 235,
    "Advances to suppliers of capital goods": 236,
    "Security deposits with government departments": 237,
    "Other non current assets": 238,
    "Sundry Creditors for goods": 242,
    "Advance received from customers": 243,
    "Provision for Taxation": 244,
    "Dividend payable": 245,
    "Other statutory liabilities (due within 1 year)": 246,
    "Interest Accrued but not due": 247,
    "Interest Accrued and due": 248,
    "Creditors for Expenses": 249,
    "Other current liabilities": 250,
    "Arrears of cumulative dividends": 254,
    "Gratuity liability not provided for": 255,
    "Disputed excise / customs / tax liabilities": 256,
    "Bank guarantee / Letter of credit outstanding": 257,
    "Other contingent liabilities": 258,
}

# Combined lookup for convenience
ALL_FIELD_TO_ROW: dict[str, int] = {**PNL_FIELD_TO_ROW, **BS_FIELD_TO_ROW}
